# Create volumes from vars
- name: Create Volume snapshots
  os_volume_snapshot:
    state: present
    volumes: '{{ item.vol_name }}'
    display_name: "{{ item.vol_name }}-{{ lookup('pip', 'date +%Y-%m-%d-%H-%M-%S') }}"
    wait: yes
    timeout: 700
    force: yes
    availability_zone: '{{ availability_zone }}'
  loop: '{{ volumes }}'