#common vars
availability_zone: melbourne-qh2-uom

lineinfile:
  dest: /etc/environment
  state: present
  line: 'export http_proxy=http://wwwproxy.unimelb.edu.au:8000'
  create: yes

lineinfile:
  dest: /etc/environment
  state: present
  line: 'export https_proxy=http://wwwproxy.unimelb.edu.au:8000'

lineinfile:
  dest: /etc/environment
  state: present
  line: 'export ftp_proxy=http://wwwproxy.unimelb.edu.au:8000'

vers:
  proxy_env:
    https_proxy: http://wwwproxy.unimelb.edu.au:8000
    http_proxy: http://wwwproxy.unimelb.edu.au:8000
    ftp_proxy: http://wwwproxy.unimelb.edu.au:8000

tasks:
  - apt: name=cobbler state=installed
    environment: "{{proxy_env}}"

#volume
volumes:
  - vol_name: webServer-volume
    vol_size: 50

# Security groups
security_groups:
  - name: webServer_ssh
    description: "Adding SSH access to web Server"
    protocol: tcp
    port_range_min: 22
    port_range_max: 22
    remote_ip_prefix: 0.0.0.0/0
  - name: webServer_http
    description: "Adding HTTP access to web Server"
    protocol: tcp
    port_range_min: 80
    port_range_max: 80
    remote_ip_prefix: 0.0.0.0/0

#instance
instance_name: web_server
instance_image: 4c5b48a0-fb86-4f4f-a98b-81e3af15e2eb  
instance_key_name: webServer
instance_flavor: uom.mse.2c9g

